//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTDSEntities : DbContext
    {
        public MTDSEntities()
            : base("name=MTDSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Asset { get; set; }
        public virtual DbSet<AssetColumn> AssetColumn { get; set; }
        public virtual DbSet<BillColumns> BillColumns { get; set; }
        public virtual DbSet<BillComments> BillComments { get; set; }
        public virtual DbSet<BillTypes> BillTypes { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleRights> RoleRights { get; set; }
        public virtual DbSet<SubAsset> SubAsset { get; set; }
        public virtual DbSet<SystemCategory> SystemCategory { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
    }
}
